### ISSUE TITLE
Add support for Geopoints

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/feature-requests#277] opened 2017-06-26 12:36 UTC
Basics:
- Create a Type to store Geopoints in one field (long/lat/alt)
- Create basic filters for Geopoints (radius, rectangle)

Bonus:
- Build goodies (like a `getMaplink` query or field parameter on a Geopoint field to get a google maps link to a Geopoint, and `drivingDistance` instead of `radius` using Google maps API in the backend)

**Comment by marktani** [comment] 2017-06-26 13:31
Closing as duplicate of #28. 🙂

**Closed by marktani** 2017-06-26 13:31 UTC

**Comment by kbrandwijk** [comment] 2017-06-26 13:33
Github issue search :-1:...
