### ISSUE TITLE
Support relations as Mutation Callback triggers

### ISSUE THREAD

**Issue by schickling** [graphcool/feature-requests#14] opened 2016-10-02 19:01 UTC

**Comment by mypark** [comment] 2016-11-26 15:38
is this a duplicate of #34 ?

**Comment by schickling** [comment] 2016-11-26 15:44
Yes it is! I'll close #34 in favor of this as we're already working on this.

**Comment by marktani** [comment] 2017-06-04 14:22
Because mutation callbacks will be replaced by Server-Side Subscriptions that follow the Subscription API, I'll close this in favor of #146.

**Closed by marktani** 2017-06-04 14:22 UTC
Labels: area/functions, area/schema, kind/improvement, stage/waiting
