### ISSUE TITLE
"Required" constraint for a relation

### ISSUE THREAD

**Issue by mypark** [graphcool/feature-requests#49] opened 2016-12-14 12:44 UTC
Example - A post object is required to have an author.

In this case a Post's relation to the user via the Author field should be required.

The required constraint functionality exists currently for fields but not for relations.

**Comment by schickling** [comment] 2016-12-19 15:11
Closing as a duplicate of #41. This improvement should land fairly soon! 🎉

**Closed by schickling** 2016-12-19 15:11 UTC
Labels: area/schema
