### ISSUE TITLE
Make permission queries filter results

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/feature-requests#294] opened 2017-07-01 00:25 UTC
**Current behavior**
If you set up a `READ` permission query, you have to make sure that when you query that Type, you use the exact same filter. If the result contains 1+ records that you are not allowed to see, you don't get any results.
This is undesirable, because it means you need to duplicate the logic of the permission query in a client side query filter. This is sometimes hard, or impossible to do.

**Desired behavior**
If the result of a permission query means you can't see a node, don't include it in the results, but do include the nodes that I can see.

**Comment by marktani** [comment] 2017-07-01 13:12
closed as duplicate of #178.

**Closed by marktani** 2017-07-01 13:12 UTC
