### ISSUE TITLE
Generate mutation queries that allow object instead of seperate fields

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/feature-requests#258] opened 2017-06-18 12:00 UTC
Currently, a mutation requires each field as a seperate parameter, like:

```
mutation {
    createPost(title: "test", description: "this is a description")
    {
        id
    }
}
```
It would be easier on the client to also have a mutation that allows you to pass the entire object as a parameter:
```
mutation {
    createPost({ "title": "test", "description": "this is a description" })
    {
        id
    }
}
```
This way you don't have to split up all the fields if you happen to have an object already.

**Comment by marktani** [comment] 2017-06-18 15:42
Closing as duplicate of https://github.com/graphcool/feature-requests/issues/38.

**Closed by marktani** 2017-06-18 15:42 UTC
