### ISSUE TITLE
invite by email should send an email

### ISSUE THREAD

**Issue by stlbucket** [graphcool/feature-requests#197] opened 2017-05-09 04:35 UTC
if an email is not associated with an existing graph.cool user, there is an error indicating they are not a graph.cool user.

shouldn't this send them an email inviting them to the graph.cool platform?

**Comment by sedubois** [comment] 2017-05-09 06:10
Yes this is a duplicate of #105

**Comment by marktani** [comment] 2017-05-09 08:29
Thanks for the suggestion! I'll close this in favor of #105.

**Closed by marktani** 2017-05-09 08:29 UTC
